/**
 * Utility function for exhaustive type checking
 */
function assertNever(x: never): never {
    throw new Error(`Unexpected object: ${x}`);
}

export interface ParameterSchemaEntry {
  key: string;
  label: string;
  type: 'number' | 'string' | 'boolean' | 'select' | 'slider' | 'multiselect';
  uiComponent?: 'NumberInput' | 'TextInput' | 'Checkbox' | 'Select' | 'Slider' | 'CheckboxGroup' | 'RangeSlider' | 'MultiSelect';
  defaultValue: any;
  options?: { value: string; label: string }[];
  step: 'BasicFundConfig' | 'AdvancedParameters' | 'GPEconomics' | 'MarketConditions' | 'AnalysisSettings' | 'ReviewSubmit';
  section: string;
  validation?: { min?: number; max?: number; required?: boolean };
}

// Master schema defining each parameter in the Parameter Wizard
export const parameterSchema: ParameterSchemaEntry[] = [
  // BasicFundConfig step
  {
    key: 'fund_size',
    label: 'Fund Size',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 100000000,
    step: 'BasicFundConfig',
    section: 'Fund Configuration',
    validation: { min: 1000000, required: true },
  },
  {
    key: 'fund_term',
    label: 'Fund Term (years)',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 10,
    step: 'BasicFundConfig',
    section: 'Fund Configuration',
    validation: { min: 1, required: true },
  },
  {
    key: 'waterfall_structure',
    label: 'Waterfall Structure',
    type: 'string',
    uiComponent: 'Select',
    options: [
      { value: 'european', label: 'European Waterfall' },
      { value: 'american', label: 'American Waterfall' },
    ],
    defaultValue: 'european',
    step: 'BasicFundConfig',
    section: 'Fund Configuration',
    validation: { required: true },
  },
  {
    key: 'management_fee_basis',
    label: 'Management Fee Basis',
    type: 'string',
    uiComponent: 'Select',
    options: [
      { value: 'committed_capital', label: 'Committed Capital' },
      { value: 'invested_capital', label: 'Invested Capital' },
      { value: 'net_asset_value', label: 'Net Asset Value (NAV)' },
      { value: 'stepped', label: 'Stepped (Declining)' },
    ],
    defaultValue: 'committed_capital',
    step: 'BasicFundConfig',
    section: 'Fund Configuration',
    validation: {},
  },
  {
    key: 'hurdle_rate',
    label: 'Hurdle Rate',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0,
    step: 'BasicFundConfig',
    section: 'Fund Configuration',
    validation: { min: 0, max: 0.2, required: true },
  },
  {
    key: 'carried_interest_rate',
    label: 'Carried Interest Rate',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0,
    step: 'BasicFundConfig',
    section: 'Fund Configuration',
    validation: { min: 0, max: 0.3, required: true },
  },
  {
    key: 'management_fee_rate',
    label: 'Management Fee Rate',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.02,
    step: 'BasicFundConfig',
    section: 'Fund Configuration',
    validation: { min: 0.01, max: 0.05 },
  },
  {
    key: 'gp_commitment_percentage',
    label: 'GP Commitment',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0,
    step: 'BasicFundConfig',
    section: 'Fund Configuration',
    validation: { min: 0, max: 0.1 },
  },
  // Zone Allocation Targets
  {
    key: 'zone_targets.green',
    label: 'Green Zone',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.6,
    step: 'BasicFundConfig',
    section: 'Zone Allocation Targets',
    validation: { min: 0, max: 1 },
  },
  {
    key: 'zone_targets.orange',
    label: 'Orange Zone',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.3,
    step: 'BasicFundConfig',
    section: 'Zone Allocation Targets',
    validation: { min: 0, max: 1 },
  },
  {
    key: 'zone_targets.red',
    label: 'Red Zone',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.1,
    step: 'BasicFundConfig',
    section: 'Zone Allocation Targets',
    validation: { min: 0, max: 1 },
  },
  // -------- NEW PARAMETERS ADDED BELOW THIS LINE --------
  // Add deployment_monthly_granularity to basic config
  {
    key: 'deployment_monthly_granularity',
    label: 'Monthly Deployment Granularity',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'BasicFundConfig',
    section: 'Deployment',
    validation: {},
  },
  // Monte Carlo simulation parameters
  {
    key: 'monte_carlo_enabled',
    label: 'Monte Carlo Enabled',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    options: [],
    step: 'AnalysisSettings',
    section: 'Analysis Settings',
    validation: {},
  },
  {
    key: 'num_simulations',
    label: 'Number of Simulations',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 1000,
    step: 'AnalysisSettings',
    section: 'Monte Carlo Parameters',
    validation: { min: 100, max: 10000 },
  },
  {
    key: 'num_processes',
    label: 'Number of Processes',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 4,
    step: 'AnalysisSettings',
    section: 'Monte Carlo Parameters',
    validation: { min: 1, max: 16 },
  },
  {
    key: 'random_seed',
    label: 'Random Seed',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: null,
    step: 'AnalysisSettings',
    section: 'Monte Carlo Parameters',
    validation: {},
  },
  {
    key: 'distribution_type',
    label: 'Distribution Type',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'normal',
    options: [
      { value: 'normal', label: 'Normal Distribution' },
      { value: 'lognormal', label: 'Log-Normal Distribution' },
      { value: 'triangular', label: 'Triangular Distribution' },
    ],
    step: 'AnalysisSettings',
    section: 'Monte Carlo Parameters',
    validation: {},
  },
  {
    key: 'convergence_analysis',
    label: 'Convergence Analysis',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'AnalysisSettings',
    section: 'Monte Carlo Parameters',
    validation: {},
  },
  {
    key: 'convergence_tolerance',
    label: 'Convergence Tolerance',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.01,
    step: 'AnalysisSettings',
    section: 'Monte Carlo Parameters',
    validation: { min: 0.001, max: 0.05 },
  },
  {
    key: 'cache_simulations',
    label: 'Cache Simulations',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: true,
    step: 'AnalysisSettings',
    section: 'Monte Carlo Parameters',
    validation: {},
  },
  {
    key: 'inner_monte_carlo_enabled',
    label: 'Enable Inner Monte Carlo',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'AnalysisSettings',
    section: 'Monte Carlo Parameters',
    validation: {},
  },
  {
    key: 'num_inner_simulations',
    label: 'Inner Simulation Runs',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 100,
    step: 'AnalysisSettings',
    section: 'Monte Carlo Parameters',
    validation: { min: 1, max: 1000 },
  },
  // Default Correlation parameters
  {
    key: 'default_correlation.enabled',
    label: 'Enable Default Correlation',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: true,
    step: 'AdvancedParameters',
    section: 'Default Correlation',
    validation: {},
  },
  {
    key: 'default_correlation.same_zone',
    label: 'Default Correlation (Same Zone)',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.3,
    step: 'AdvancedParameters',
    section: 'Default Correlation',
    validation: { min: 0, max: 1 },
  },
  {
    key: 'default_correlation.cross_zone',
    label: 'Default Correlation (Cross Zone)',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.1,
    step: 'AdvancedParameters',
    section: 'Default Correlation',
    validation: { min: 0, max: 1 },
  },
  // Zone Rebalancing parameters
  {
    key: 'zone_rebalancing_enabled',
    label: 'Enable Zone Rebalancing',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: true,
    step: 'AdvancedParameters',
    section: 'Zone Rebalancing',
    validation: {},
  },
  {
    key: 'rebalancing_strength',
    label: 'Rebalancing Strength',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.5,
    step: 'AdvancedParameters',
    section: 'Zone Rebalancing',
    validation: { min: 0, max: 1 },
  },
  {
    key: 'zone_drift_threshold',
    label: 'Zone Drift Threshold',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.1,
    step: 'AdvancedParameters',
    section: 'Zone Rebalancing',
    validation: { min: 0, max: 0.5 },
  },
  {
    key: 'zone_allocation_precision',
    label: 'Zone Allocation Precision',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.8,
    step: 'AdvancedParameters',
    section: 'Zone Rebalancing',
    validation: { min: 0, max: 1 },
  },
  // Market Conditions
  {
    key: 'market_conditions_by_year',
    label: 'Market Conditions by Year',
    type: 'string', // Will be handled by a custom component
    uiComponent: 'TextInput', // Placeholder, will use custom component in UI
    defaultValue: {},
    step: 'MarketConditions',
    section: 'Market Conditions',
    validation: {},
  },
  {
    key: 'housing_market_pattern',
    label: 'Housing Market Pattern',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'stable',
    options: [
      { value: 'stable', label: 'Stable Throughout' },
      { value: 'improving', label: 'Gradually Improving' },
      { value: 'declining', label: 'Gradually Declining' },
      { value: 'cycle', label: 'Full Market Cycle' },
      { value: 'custom', label: 'Custom (Set Per Year)' },
    ],
    step: 'MarketConditions',
    section: 'Market Patterns',
    validation: {},
  },
  {
    key: 'interest_rate_pattern',
    label: 'Interest Rate Pattern',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'stable',
    options: [
      { value: 'stable', label: 'Stable Throughout' },
      { value: 'rising', label: 'Gradually Rising' },
      { value: 'falling', label: 'Gradually Falling' },
      { value: 'cycle', label: 'Full Cycle (Rise then Fall)' },
      { value: 'custom', label: 'Custom (Set Per Year)' },
    ],
    step: 'MarketConditions',
    section: 'Market Patterns',
    validation: {},
  },
  {
    key: 'economic_outlook_pattern',
    label: 'Economic Outlook Pattern',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'stable',
    options: [
      { value: 'stable', label: 'Stable Throughout' },
      { value: 'improving', label: 'Gradually Improving' },
      { value: 'declining', label: 'Gradually Declining' },
      { value: 'cycle', label: 'Full Economic Cycle' },
      { value: 'custom', label: 'Custom (Set Per Year)' },
    ],
    step: 'MarketConditions',
    section: 'Market Patterns',
    validation: {},
  },
  // Lifecycle Parameters
  {
    key: 'avg_loan_exit_year',
    label: 'Average Loan Exit Year',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 5,
    step: 'AdvancedParameters',
    section: 'Lifecycle Timing',
    validation: { min: 1 },
  },
  {
    key: 'exit_year_std_dev',
    label: 'Exit Year Std Dev',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 1.5,
    step: 'AdvancedParameters',
    section: 'Lifecycle Timing',
    validation: { min: 0 },
  },
  {
    key: 'min_holding_period',
    label: 'Minimum Holding Period',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 0.25,
    step: 'AdvancedParameters',
    section: 'Lifecycle Timing',
    validation: { min: 0 },
  },
  {
    key: 'exit_year_skew',
    label: 'Exit Year Skew',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0,
    step: 'AdvancedParameters',
    section: 'Lifecycle Timing',
    validation: { min: -2, max: 2 },
  },
  // Lifecycle Simulation
  {
    key: 'simulate_full_lifecycle',
    label: 'Simulate Full Lifecycle',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'AdvancedParameters',
    section: 'Lifecycle Simulation',
    validation: {},
  },
  {
    key: 'enable_reinvestments',
    label: 'Enable Reinvestments',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'AdvancedParameters',
    section: 'Lifecycle Simulation',
    validation: {},
  },
  {
    key: 'enable_defaults',
    label: 'Enable Defaults',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'AdvancedParameters',
    section: 'Lifecycle Simulation',
    validation: {},
  },
  {
    key: 'enable_early_repayments',
    label: 'Enable Early Repayments',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'AdvancedParameters',
    section: 'Lifecycle Simulation',
    validation: {},
  },
  {
    key: 'enable_appreciation',
    label: 'Enable Appreciation',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'AdvancedParameters',
    section: 'Lifecycle Simulation',
    validation: {},
  },
  {
    key: 'early_exit_probability',
    label: 'Early Exit Probability',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.1,
    step: 'AdvancedParameters',
    section: 'Lifecycle Simulation',
    validation: { min: 0, max: 1 },
  },
  {
    key: 'reinvestment_rate',
    label: 'Reinvestment Rate',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.8,
    step: 'AdvancedParameters',
    section: 'Lifecycle Simulation',
    validation: { min: 0, max: 1 },
  },
  // Default rates
  {
    key: 'default_rates.green',
    label: 'Default Rate (Green)',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.01,
    step: 'AdvancedParameters',
    section: 'Default Rates',
    validation: { min: 0, max: 0.1 },
  },
  {
    key: 'default_rates.orange',
    label: 'Default Rate (Orange)',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.03,
    step: 'AdvancedParameters',
    section: 'Default Rates',
    validation: { min: 0, max: 0.2 },
  },
  {
    key: 'default_rates.red',
    label: 'Default Rate (Red)',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.05,
    step: 'AdvancedParameters',
    section: 'Default Rates',
    validation: { min: 0, max: 0.3 },
  },
  // Appreciation rates
  {
    key: 'appreciation_rates.green',
    label: 'Green Zone Appreciation Rate',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.03,
    step: 'AdvancedParameters',
    section: 'Appreciation Rates',
    validation: { min: 0, max: 0.1 },
  },
  {
    key: 'appreciation_rates.orange',
    label: 'Orange Zone Appreciation Rate',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.04,
    step: 'AdvancedParameters',
    section: 'Appreciation Rates',
    validation: { min: 0, max: 0.15 },
  },
  {
    key: 'appreciation_rates.red',
    label: 'Red Zone Appreciation Rate',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.05,
    step: 'AdvancedParameters',
    section: 'Appreciation Rates',
    validation: { min: 0, max: 0.2 },
  },
  {
    key: 'appreciation_share_method',
    label: 'Appreciation Share Method',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'fixed_rate',
    options: [
      { value: 'fixed_rate', label: 'Fixed Rate' },
      { value: 'ltv_based', label: 'LTV Based' },
    ],
    step: 'AdvancedParameters',
    section: 'Appreciation Rates',
    validation: {},
  },
  {
    key: 'property_value_discount_rate',
    label: 'Property Value Discount Rate',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0,
    step: 'AdvancedParameters',
    section: 'Appreciation Rates',
    validation: { min: 0, max: 0.3 },
  },
  {
    key: 'appreciation_base',
    label: 'Appreciation Base',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'discounted_value',
    options: [
      { value: 'discounted_value', label: 'Discounted Value' },
      { value: 'market_value', label: 'Market Value' },
    ],
    step: 'AdvancedParameters',
    section: 'Appreciation Rates',
    validation: {},
  },
  {
    key: 'use_tls_zone_growth',
    label: 'Use Suburb-level Growth Rates',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'AdvancedParameters',
    section: 'Appreciation Rates',
    validation: {},
  },
  // -----------------------------------------------------------------------
  // Leverage – Capital Structure (NAV facility, notes, ramp line)
  // -----------------------------------------------------------------------
  {
    key: 'leverage.green_sleeve.enabled',
    label: 'Enable NAV Facility',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: true,
    step: 'AdvancedParameters',
    section: 'Leverage',
    validation: {},
  },
  {
    key: 'leverage.green_sleeve.max_mult',
    label: 'Max Multiple (×NAV)',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 1.5,
    step: 'AdvancedParameters',
    section: 'Leverage',
    validation: { min: 0, max: 2 },
  },
  {
    key: 'leverage.green_sleeve.spread_bps',
    label: 'Spread (bps)',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 275,
    step: 'AdvancedParameters',
    section: 'Leverage',
    validation: { min: 0, max: 1000 },
  },
  {
    key: 'leverage.green_sleeve.commitment_fee_bps',
    label: 'Commitment Fee (bps)',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 50,
    step: 'AdvancedParameters',
    section: 'Leverage',
    validation: { min: 0, max: 200 },
  },
  {
    key: 'leverage.a_plus_overadvance.enabled',
    label: 'Enable Over-Advance (A+)',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'AdvancedParameters',
    section: 'Leverage',
    validation: {},
  },
  {
    key: 'leverage.a_plus_overadvance.advance_rate',
    label: 'Advance Rate (0-1)',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 0.75,
    step: 'AdvancedParameters',
    section: 'Leverage',
    validation: { min: 0, max: 1 },
  },
  {
    key: 'leverage.deal_note.enabled',
    label: 'Enable Deal Note',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'AdvancedParameters',
    section: 'Leverage',
    validation: {},
  },
  {
    key: 'leverage.deal_note.note_pct',
    label: 'Note % of Value',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 0.3,
    step: 'AdvancedParameters',
    section: 'Leverage',
    validation: { min: 0, max: 1 },
  },
  {
    key: 'leverage.deal_note.note_rate',
    label: 'Note Rate',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 0.07,
    step: 'AdvancedParameters',
    section: 'Leverage',
    validation: { min: 0, max: 0.2 },
  },
  {
    key: 'leverage.ramp_line.enabled',
    label: 'Enable Ramp Line',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'AdvancedParameters',
    section: 'Leverage',
    validation: {},
  },
  {
    key: 'leverage.ramp_line.limit_pct_commit',
    label: 'Ramp Limit % Commit',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 0.15,
    step: 'AdvancedParameters',
    section: 'Leverage',
    validation: { min: 0, max: 1 },
  },
  {
    key: 'leverage.ramp_line.draw_period_months',
    label: 'Draw Period (months)',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 24,
    step: 'AdvancedParameters',
    section: 'Leverage',
    validation: { min: 1, max: 60 },
  },
  {
    key: 'leverage.ramp_line.spread_bps',
    label: 'Ramp Spread (bps)',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 300,
    step: 'AdvancedParameters',
    section: 'Leverage',
    validation: { min: 0, max: 1000 },
  },
  {
    key: 'leverage.dynamic_rules',
    label: 'Dynamic Leverage Rules (JSON)',
    type: 'string',
    uiComponent: 'TextInput',
    defaultValue: '[]',
    step: 'AdvancedParameters',
    section: 'Leverage',
    validation: {},
  },
  // Distribution settings
  {
    key: 'distribution_frequency',
    label: 'Distribution Frequency',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'annual',
    options: [
      { value: 'annual', label: 'Annual' },
      { value: 'semi_annual', label: 'Semi-Annual' },
      { value: 'quarterly', label: 'Quarterly' }
    ],
    step: 'AdvancedParameters',
    section: 'Distribution Settings',
    validation: { required: true },
  },
  {
    key: 'management_fee_offset_percentage',
    label: 'Management Fee Offset %',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.0,
    step: 'AdvancedParameters',
    section: 'Management Fees',
    validation: { min: 0, max: 1 },
  },
  // Sensitivity Analysis
  {
    key: 'sensitivity_analysis_enabled',
    label: 'Enable Sensitivity Analysis',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'AnalysisSettings',
    section: 'Sensitivity Analysis',
    validation: {},
  },
  {
    key: 'sensitivity_parameters',
    label: 'Parameters to Analyze',
    type: 'multiselect',
    uiComponent: 'MultiSelect',
    defaultValue: ['fund_size', 'hurdle_rate', 'carried_interest_rate'],
    options: [
      { value: 'fund_size', label: 'Fund Size' },
      { value: 'fund_term', label: 'Fund Term' },
      { value: 'hurdle_rate', label: 'Hurdle Rate' },
      { value: 'carried_interest_rate', label: 'Carried Interest' },
      { value: 'management_fee_rate', label: 'Management Fee' },
      { value: 'default_rates.green', label: 'Default Rate (Green)' },
      { value: 'default_rates.orange', label: 'Default Rate (Orange)' },
      { value: 'default_rates.red', label: 'Default Rate (Red)' },
      { value: 'appreciation_rates.green', label: 'Appreciation (Green)' },
      { value: 'appreciation_rates.orange', label: 'Appreciation (Orange)' },
      { value: 'appreciation_rates.red', label: 'Appreciation (Red)' },
    ],
    step: 'AnalysisSettings',
    section: 'Sensitivity Analysis',
    validation: {},
  },
  {
    key: 'sensitivity_range_percent',
    label: 'Sensitivity Range (%)',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 20,
    step: 'AnalysisSettings',
    section: 'Sensitivity Analysis',
    validation: { min: 5, max: 50 },
  },
  {
    key: 'sensitivity_steps',
    label: 'Number of Steps',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 5,
    step: 'AnalysisSettings',
    section: 'Sensitivity Analysis',
    validation: { min: 3, max: 10 },
  },
  // Performance Metrics
  {
    key: 'risk_free_rate',
    label: 'Risk-Free Rate',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.03,
    step: 'AnalysisSettings',
    section: 'Performance Metrics',
    validation: { min: 0, max: 0.1 },
  },
  {
    key: 'target_irr',
    label: 'Target IRR',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.15,
    step: 'AnalysisSettings',
    section: 'Performance Metrics',
    validation: { min: 0, max: 0.3 },
  },
  {
    key: 'target_equity_multiple',
    label: 'Target Equity Multiple',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 1.8,
    step: 'AnalysisSettings',
    section: 'Performance Metrics',
    validation: { min: 1, max: 3 },
  },
  {
    key: 'target_distribution_yield',
    label: 'Target Distribution Yield',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.07,
    step: 'AnalysisSettings',
    section: 'Performance Metrics',
    validation: { min: 0, max: 0.15 },
  },
  {
    key: 'performance_metrics_display',
    label: 'Metrics to Display',
    type: 'string',
    uiComponent: 'CheckboxGroup',
    defaultValue: ['irr', 'equity_multiple', 'roi', 'payback_period', 'distribution_yield'],
    options: [
      { value: 'irr', label: 'IRR' },
      { value: 'equity_multiple', label: 'Equity Multiple' },
      { value: 'roi', label: 'ROI' },
      { value: 'payback_period', label: 'Payback Period' },
      { value: 'dpi', label: 'DPI' },
      { value: 'tvpi', label: 'TVPI' },
    ],
    step: 'AnalysisSettings',
    section: 'Performance Metrics',
    validation: {},
  },
  // GP Entity - Dividend Policy
  {
    key: 'gp_entity.dividend_policy.enabled',
    label: 'Enable Dividend Distribution',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'GPEconomics',
    section: 'Dividend Policy',
    validation: {},
  },
  {
    key: 'gp_entity.dividend_policy.type',
    label: 'Dividend Policy Type',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'percentage',
    options: [
      { value: 'percentage', label: 'Percentage of Net Income' },
      { value: 'fixed', label: 'Fixed Amount' },
      { value: 'residual', label: 'Residual Cash Flow' },
    ],
    step: 'GPEconomics',
    section: 'Dividend Policy',
    validation: {},
  },
  {
    key: 'gp_entity.dividend_policy.percentage',
    label: 'Dividend Percentage',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.5,
    step: 'GPEconomics',
    section: 'Dividend Policy',
    validation: { min: 0, max: 1 },
  },
  // GP Entity - Team Allocation
  {
    key: 'gp_entity.team_allocation.partner_percentage',
    label: 'Partner Allocation Percentage',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.7,
    step: 'GPEconomics',
    section: 'Team Allocation',
    validation: { min: 0, max: 1 },
  },
  {
    key: 'gp_entity.team_allocation.employee_percentage',
    label: 'Employee Allocation Percentage',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.3,
    step: 'GPEconomics',
    section: 'Team Allocation',
    validation: { min: 0, max: 1 },
  },
  // GP Entity - Management Company
  {
    key: 'gp_entity.management_company.base_expenses',
    label: 'Base Annual Expenses',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 500000,
    step: 'GPEconomics',
    section: 'Management Company',
    validation: { min: 0 },
  },
  {
    key: 'gp_entity.management_company.expense_growth_rate',
    label: 'Expense Growth Rate',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.03,
    step: 'GPEconomics',
    section: 'Management Company',
    validation: { min: 0, max: 0.1 },
  },
  // Add detailed management company expense items
  {
    key: 'gp_entity.management_company.office_expenses',
    label: 'Office Expenses',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 100000,
    step: 'GPEconomics',
    section: 'Management Company',
    validation: { min: 0 },
  },
  {
    key: 'gp_entity.management_company.technology_expenses',
    label: 'Technology Expenses',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 50000,
    step: 'GPEconomics',
    section: 'Management Company',
    validation: { min: 0 },
  },
  {
    key: 'gp_entity.management_company.marketing_expenses',
    label: 'Marketing Expenses',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 50000,
    step: 'GPEconomics',
    section: 'Management Company',
    validation: { min: 0 },
  },
  {
    key: 'gp_entity.management_company.legal_expenses',
    label: 'Legal Expenses',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 100000,
    step: 'GPEconomics',
    section: 'Management Company',
    validation: { min: 0 },
  },
  {
    key: 'gp_entity.management_company.other_expenses',
    label: 'Other Expenses',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 200000,
    step: 'GPEconomics',
    section: 'Management Company',
    validation: { min: 0 },
  },
  {
    key: 'gp_entity.monthly_patterns.management_fees',
    label: 'Management Fee Monthly Pattern',
    type: 'string',
    uiComponent: 'TextInput',
    defaultValue: '[]',
    step: 'GPEconomics',
    section: 'Management Company',
    validation: {},
  },
  {
    key: 'gp_entity.monthly_patterns.carried_interest',
    label: 'Carried Interest Monthly Pattern',
    type: 'string',
    uiComponent: 'TextInput',
    defaultValue: '[]',
    step: 'GPEconomics',
    section: 'Management Company',
    validation: {},
  },
  {
    key: 'gp_entity.monthly_patterns.origination_fees',
    label: 'Origination Fee Monthly Pattern',
    type: 'string',
    uiComponent: 'TextInput',
    defaultValue: '[]',
    step: 'GPEconomics',
    section: 'Management Company',
    validation: {},
  },
  {
    key: 'gp_entity.monthly_patterns.additional_revenue',
    label: 'Additional Revenue Monthly Pattern',
    type: 'string',
    uiComponent: 'TextInput',
    defaultValue: '[]',
    step: 'GPEconomics',
    section: 'Management Company',
    validation: {},
  },
  {
    key: 'gp_entity.monthly_patterns.base_expenses',
    label: 'Base Expense Monthly Pattern',
    type: 'string',
    uiComponent: 'TextInput',
    defaultValue: '[]',
    step: 'GPEconomics',
    section: 'Management Company',
    validation: {},
  },
  // Reporting and Export
  {
    key: 'report_template',
    label: 'Report Template',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'summary',
    options: [
      { value: 'summary', label: 'Summary Report' },
      { value: 'detailed', label: 'Detailed Report' },
      { value: 'investor', label: 'Investor Report' },
      { value: 'risk', label: 'Risk Analysis Report' },
    ],
    step: 'ReviewSubmit',
    section: 'Reporting',
    validation: {},
  },
  {
    key: 'report_title',
    label: 'Report Title',
    type: 'string',
    uiComponent: 'TextInput',
    defaultValue: 'Fund Simulation Report',
    step: 'ReviewSubmit',
    section: 'Reporting',
    validation: {},
  },
  {
    key: 'export_format',
    label: 'Export Format',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'json',
    options: [
      { value: 'json', label: 'JSON' },
      { value: 'csv', label: 'CSV' },
      { value: 'excel', label: 'Excel' },
      { value: 'pdf', label: 'PDF' },
    ],
    step: 'ReviewSubmit',
    section: 'Reporting',
    validation: {},
  },
  {
    key: 'include_charts',
    label: 'Include Charts',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: true,
    step: 'ReviewSubmit',
    section: 'Reporting',
    validation: {},
  },
  // Keep previously defined entries below
  {
    key: 'optimization_enabled',
    label: 'Optimization Enabled',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    options: [],
    step: 'AnalysisSettings',
    section: 'Analysis Settings',
    validation: {},
  },
  {
    key: 'generate_efficient_frontier',
    label: 'Generate Efficient Frontier',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    options: [],
    step: 'AnalysisSettings',
    section: 'Analysis Settings',
    validation: {},
  },
  {
    key: 'efficient_frontier_points',
    label: 'Efficient Frontier Points',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 50,
    step: 'AnalysisSettings',
    section: 'Analysis Settings',
    validation: { min: 1, max: 100 },
  },
  {
    key: 'stress_testing_enabled',
    label: 'Stress Testing Enabled',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'AnalysisSettings',
    section: 'Stress Testing',
    validation: {},
  },
  {
    key: 'external_data_enabled',
    label: 'External Data Enabled',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    options: [],
    step: 'AnalysisSettings',
    section: 'Analysis Settings',
    validation: {},
  },
  {
    key: 'generate_reports',
    label: 'Generate Reports',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    options: [],
    step: 'ReviewSubmit',
    section: 'Review & Submit',
    validation: {},
  },
  {
    key: 'management_fee_step_down',
    label: 'Management Fee Step Down',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    options: [],
    step: 'AdvancedParameters',
    section: 'Management Fees',
    validation: {},
  },
  {
    key: 'management_fee_step_down_year',
    label: 'Management Fee Step Down Year',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 5,
    step: 'AdvancedParameters',
    section: 'Management Fees',
    validation: { min: 1 },
  },
  {
    key: 'management_fee_step_down_rate',
    label: 'Management Fee Step Down Rate',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.5,
    step: 'AdvancedParameters',
    section: 'Management Fees',
    validation: { min: 0, max: 1 },
  },
  {
    key: 'deployment_pace',
    label: 'Deployment Pace',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'even',
    options: [
      { value: 'even', label: 'Even (Linear)' },
      { value: 'front_loaded', label: 'Front-Loaded (Faster Early)' },
      { value: 'back_loaded', label: 'Back-Loaded (Faster Later)' },
      { value: 'bell_curve', label: 'Bell Curve (Faster in Middle)' }
    ],
    step: 'AdvancedParameters',
    section: 'Deployment',
    validation: {},
  },
  {
    key: 'deployment_period',
    label: 'Deployment Period',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 3,
    step: 'AdvancedParameters',
    section: 'Deployment',
    validation: { min: 1 },
  },
  {
    key: 'deployment_period_unit',
    label: 'Deployment Period Unit',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'years',
    options: [
      { value: 'years', label: 'Years' },
      { value: 'quarters', label: 'Quarters' },
      { value: 'months', label: 'Months' },
    ],
    step: 'AdvancedParameters',
    section: 'Deployment',
    validation: { required: true },
  },
  {
    key: 'average_ltv',
    label: 'Average LTV',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.65,
    step: 'AdvancedParameters',
    section: 'LTV Distribution',
    validation: { min: 0.1, max: 0.9 },
  },
  {
    key: 'ltv_std_dev',
    label: 'LTV Standard Deviation',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.05,
    step: 'AdvancedParameters',
    section: 'LTV Distribution',
    validation: { min: 0.01, max: 0.2 },
  },
  {
    key: 'min_ltv',
    label: 'Minimum LTV',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.5,
    step: 'AdvancedParameters',
    section: 'LTV Distribution',
    validation: { min: 0.1, max: 0.9 },
  },
  {
    key: 'max_ltv',
    label: 'Maximum LTV',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.8,
    step: 'AdvancedParameters',
    section: 'LTV Distribution',
    validation: { min: 0.1, max: 0.95 },
  },
  {
    key: 'catch_up_rate',
    label: 'Catch-Up Rate',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.2,
    step: 'AdvancedParameters',
    section: 'Distribution Settings',
    validation: { min: 0, max: 1 },
  },
  {
    key: 'catch_up_structure',
    label: 'Catch-Up Structure',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'full',
    options: [
      { value: 'none', label: 'None' },
      { value: 'partial', label: 'Partial' },
      { value: 'full', label: 'Full' },
    ],
    step: 'AdvancedParameters',
    section: 'Distribution Settings',
    validation: {},
  },
  {
    key: 'preferred_return_compounding',
    label: 'Preferred Return Compounding',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'annual',
    options: [
      { value: 'annual', label: 'Annual' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'continuous', label: 'Continuous' },
    ],
    step: 'AdvancedParameters',
    section: 'Distribution Settings',
    validation: { required: true },
  },
  {
    key: 'distribution_timing',
    label: 'Distribution Timing',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'end_of_year',
    options: [
      { value: 'end_of_year', label: 'End of Year' },
      { value: 'end_of_quarter', label: 'End of Quarter' },
      { value: 'end_of_month', label: 'End of Month' },
      { value: 'on_exit', label: 'On Loan Exit' },
    ],
    step: 'AdvancedParameters',
    section: 'Distribution Settings',
    validation: {},
  },
  {
    key: 'clawback_provision',
    label: 'Clawback Provision',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: true,
    step: 'AdvancedParameters',
    section: 'Distribution Settings',
    validation: {},
  },
  {
    key: 'reinvestment_logic',
    label: 'Reinvestment Logic',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'waterfall_based',
    options: [
      { value: 'waterfall_based', label: 'Waterfall Based' },
      { value: 'pro_rata', label: 'Pro-Rata' },
      { value: 'full_reinvestment', label: 'Full Reinvestment' },
    ],
    step: 'AdvancedParameters',
    section: 'Distribution Settings',
    validation: {},
  },
  {
    key: 'origination_fee_rate',
    label: 'Origination Fee Rate',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.03,
    step: 'AdvancedParameters',
    section: 'Fees',
    validation: { min: 0, max: 0.1 },
  },
  {
    key: 'origination_fee_to_gp',
    label: 'Origination Fee to GP',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: true,
    step: 'AdvancedParameters',
    section: 'Fees',
    validation: {},
  },
  {
    key: 'expense_rate',
    label: 'Expense Rate',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.005,
    step: 'AdvancedParameters',
    section: 'Fees',
    validation: { min: 0, max: 0.05 },
  },
  {
    key: 'formation_costs',
    label: 'Formation Costs',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 100000,
    step: 'AdvancedParameters',
    section: 'Fees',
    validation: { min: 0 },
  },
  // GP Entity
  {
    key: 'gp_entity.name',
    label: 'GP Entity Name',
    type: 'string',
    uiComponent: 'TextInput',
    defaultValue: 'Equihome Partners',
    step: 'GPEconomics',
    section: 'GP Entity',
    validation: {},
  },
  {
    key: 'gp_entity.cross_fund_carry',
    label: 'Cross-Fund Carry',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'GPEconomics',
    section: 'GP Entity',
    validation: {},
  },
  {
    key: 'gp_entity.initial_cash_reserve',
    label: 'Initial Cash Reserve',
    type: 'number',
    uiComponent: 'NumberInput',
    defaultValue: 0,
    step: 'GPEconomics',
    section: 'GP Entity',
    validation: { min: 0 },
  },
  {
    key: 'aggregate_gp_economics',
    label: 'Aggregate GP Economics',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: true,
    step: 'GPEconomics',
    section: 'GP Entity',
    validation: {},
  },
  // Appreciation sharing parameters missing
  {
    key: 'appreciation_sharing_method',
    label: 'Appreciation Sharing Method',
    type: 'select',
    uiComponent: 'Select',
    defaultValue: 'fixed_percentage',
    options: [
      { value: 'fixed_percentage', label: 'Fixed Percentage' },
      { value: 'ltv_based', label: 'LTV Based' },
      { value: 'tiered', label: 'Tiered' },
    ],
    step: 'AdvancedParameters',
    section: 'Appreciation Sharing',
    validation: {},
  },
  {
    key: 'appreciation_fund_share',
    label: 'Fund Share of Appreciation',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.3,
    step: 'AdvancedParameters',
    section: 'Appreciation Sharing',
    validation: { min: 0, max: 1 },
  },
  {
    key: 'property_value_discount_rate',
    label: 'Property Value Discount Rate',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.05,
    step: 'AdvancedParameters',
    section: 'Appreciation Sharing',
    validation: { min: 0, max: 0.2 },
  },
  {
    key: 'ltv_appreciation_base',
    label: 'LTV Appreciation Base',
    type: 'slider',
    uiComponent: 'Slider',
    defaultValue: 0.7,
    step: 'AdvancedParameters',
    section: 'Appreciation Sharing',
    validation: { min: 0.5, max: 0.9 },
  },

  // Stress Testing Parameters - KEEP ONLY ONE ENTRY
  {
    key: 'stress_test_scenarios',
    label: 'Stress Test Scenarios',
    type: 'multiselect',
    uiComponent: 'MultiSelect',
    defaultValue: ['recession'],
    options: [
      { value: 'recession', label: 'Recession' },
      { value: 'housing_crash', label: 'Housing Market Crash' },
      { value: 'interest_rate_spike', label: 'Interest Rate Spike' },
      { value: 'liquidity_crisis', label: 'Liquidity Crisis' },
      { value: 'combined_shock', label: 'Combined Market Shock' },
    ],
    step: 'AnalysisSettings',
    section: 'Stress Testing',
    validation: {},
  },
  {
    key: 'run_dual_leverage_comparison',
    label: 'Run Dual Leverage Comparison',
    type: 'boolean',
    uiComponent: 'Checkbox',
    defaultValue: false,
    step: 'AnalysisSettings',
    section: 'Leverage',
    validation: {},
  },
];

export const getDefaultUIComponentForType = (type: ParameterSchemaEntry['type']): NonNullable<ParameterSchemaEntry['uiComponent']> => {
    switch (type) {
        case 'number':
            return 'NumberInput';
        case 'string':
            return 'TextInput';
        case 'boolean':
            return 'Checkbox';
        case 'select':
            return 'Select';
        case 'slider':
            return 'Slider';
        case 'multiselect':
            return 'MultiSelect';
        default:
            return assertNever(type);
    }
};